; PicrossSprites constants
	const_def
	const PATTERN_NORMAL
	const PATTERN_TILESET

; PicrossMinigame.Jumptable constants
	const_def
	const PICROSS_INIT_MODE
	const PICROSS_RUN_MODE
	const PICROSS_EXIT_MODE

; wPicrossCurrentCellType constants
	const_def
	const PICROSS_BLANK_CELL
	const PICROSS_COLORED_CELL
	const PICROSS_MARKED_CELL

DEF PICROSS_GFX_BGTILE EQU $80
DEF PICROSS_GFX_BUSHTILE EQU $81
DEF PICROSS_GFX_BUSHGROUNDTILE EQU $82
DEF PICROSS_GFX_GROUNDTILE EQU $83

DEF PICROSS_GFX_COLUMNS EQU $84
DEF PICROSS_GFX_ROWS EQU $b4
DEF PICROSS_GFX_TABLESTART equ $f0


DEF NUM_PICROSS_STAGES EQU 6
DEF SPRITE_ANIM_DICT_MINIGAME_PICROSS EQU SPRITE_ANIM_DICT_ARROW_CURSOR
